name: Publish

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Compile Python
        run: |
          set -x
          sudo apt-get install gcc make curl
          curl -L -o /tmp/python-src.tgz https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz 
          tar -xvf /tmp/python-src.tgz -C /tmp
          cd /tmp/Python-3.6.5
          ./configure --with-ensurepip=install
          make -j 8
          make test
          ls -lah
